// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Kw9Yp8pM8gLW3g8UwlSO9dlS-Ej3GGU',
    appId: '1:809494714075:web:d8ccb6a86b1274de299efe',
    messagingSenderId: '809494714075',
    projectId: 'feedback-app-ddeab',
    authDomain: 'feedback-app-ddeab.firebaseapp.com',
    storageBucket: 'feedback-app-ddeab.appspot.com',
    measurementId: 'G-3VZKMMG1H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3varuHNM65D85XjtiRQsC_SA65j5juQA',
    appId: '1:809494714075:android:c6567ed376847e2d299efe',
    messagingSenderId: '809494714075',
    projectId: 'feedback-app-ddeab',
    storageBucket: 'feedback-app-ddeab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPGSM3cI0x_i2ZJTvi_dRuLPvZCBJHNN4',
    appId: '1:809494714075:ios:d9593cdcc9fe2d11299efe',
    messagingSenderId: '809494714075',
    projectId: 'feedback-app-ddeab',
    storageBucket: 'feedback-app-ddeab.appspot.com',
    iosBundleId: 'com.example.feedback1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPGSM3cI0x_i2ZJTvi_dRuLPvZCBJHNN4',
    appId: '1:809494714075:ios:7b3dfeb881ad6ff7299efe',
    messagingSenderId: '809494714075',
    projectId: 'feedback-app-ddeab',
    storageBucket: 'feedback-app-ddeab.appspot.com',
    iosBundleId: 'com.example.feedback1.RunnerTests',
  );
}
